# -*- coding: utf-8 -*-
"""Rotation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUYi9JyDGhwm-guQdMrAgMCFNtVn1TTY
"""

# ! pip install ultralytics insightface onnxruntime

import cv2
import numpy as np
from ultralytics import YOLO
from insightface.app import FaceAnalysis
import os
import pandas as pd
import csv


detector = FaceAnalysis(name='buffalo_l') # set face detector
detector.prepare(ctx_id=0, det_size=(640, 640))
card_model = YOLO('../models/CardDetection.pt') # set yolo model for card detection
lst = []

csv_file = "./angles.csv"
if not os.path.exists(csv_file):
    with open(csv_file, mode='w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["filename", "angle"])

def rotation(path):
    image = cv2.imread(path)  # set image
    results = card_model(image)  # run card yolo model for image

    if len(results[0].boxes) == 0:  # if cant recognize card
        print("No card detected!")
        print('--------------------------------------------------------------')
        print(path)
        return None

    # set 4 corner location
    x1, y1, x2, y2 = map(int, results[0].boxes[0].xyxy[0])
    cropped_card = image[y1:y2, x1:x2]

    # detect face in the cropped card
    faces = detector.get(cropped_card)

    # check for faces
    if faces:
        x1, y1, x2, y2 = map(int, faces[0]['bbox'])  # get face bounding box
        w, h = x2 - x1, y2 - y1
        face_center = (x1 + w // 2, y1 + h // 2)  # face center
        card_center = (cropped_card.shape[1] // 2, cropped_card.shape[0] // 2)  # card center

        # calculate rotation angle
        angle = np.arctan2(face_center[1] - card_center[1], face_center[0] - card_center[0]) * (180 / np.pi) + 180
        rotation_matrix = cv2.getRotationMatrix2D(card_center, angle, 1.0)
        rotated = cv2.warpAffine(cropped_card, rotation_matrix, (cropped_card.shape[1], cropped_card.shape[0]))


        # Write to CSV
        with open(csv_file, mode='a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([os.path.basename(path), round(angle, 2)])

        print(path)
        print('--------------------------------------------------------------')
        print(angle)
        cv2.imshow(rotated)
        return rotated

    print('cant find face')
    print('--------------------------------------------------------------')
    lst.append(path)
    print(path)
    cv2.imshow(cropped_card)
    return cropped_card

def run_on_folder(folder_path, extensions=[".jpg", ".jpeg", ".png"]):
    for filename in os.listdir(folder_path):
        if any(filename.lower().endswith(ext) for ext in extensions):
            file_path = os.path.join(folder_path, filename)
            rotation(file_path)

run_on_folder('../archive/iranian_national_id_card_images')
